### PR TITLE
Next9 support and working example

### PR DESCRIPTION
**Pull request by boenrobot**
With Next 9 being released recently with native TypeScript support, some changes were needed to this package that are not backwards compatible with Next 8. This PR makes them.

Also bumps the required Nest version of the example to 6.0.4, to match this package's established minimum.

NOTE: I had to comment out the cache module from the example though, as it seems Nest 6 is doing things differently, and because of that, the example fails to start (though it does build!). I've made up for that by adding a second route, and links, to illustrate how one gets SSR on initial load, and then client side navigation subsequently.

### CODE REVIEW

**Comment by kyle-mccarthy** [comment]
Hey thank you for doing this -- I really appreciate it! I am going to test this and remove the whole cache module stuff in this example. If everything is good I will merge this and do a major version bump!

**Comment by kyle-mccarthy** [comment]
Are you wanting for me to merge this PR or the other one? To make this easier to review and test, I would prefer to have one PR that actually makes changes to the libs code and then one that updates examples. LMK what I can do to help, thanks!

**Comment by kyle-mccarthy** [comment]
Separate commits work as well. I just want to make it easy for people to see what changed in the library between versions separate of the example changes. 

If an organization has policies around library updates it will be clear what changes they need to look at vs changes in documentation.

**Comment by jakesyl** [comment]
@boenrobot this is fantastic!

**Comment by kyle-mccarthy** [comment]
@boenrobot I wanted to let you know I finally got this merged yesterday. I made some changes to the example to simplify it, I tried to make it as minimal as possible so people could use it as a starter w/o it being opinionated. Thank you again for contributing!

**Pull request merged**
