### PR TITLE
Fix missing nodemon dependency

### PR DESCRIPTION
**Pull request by sergioutama**
`nodemon` is missing from basic example dependency

@kyle-mccarthy there is missing dependency on the basic example and I add additional info on readme to run the example

### CODE REVIEW

**Comment by kyle-mccarthy** [comment]
Hey thanks for the contribution? Does this also fix #57?

**Comment by sergioutama** [comment]
> Hey thanks for the contribution? Does this also fix #57?

This PR does not fix the issue on monorepo.
I need to investigate more on monorepo issue, temporary fix for #57 is by locking `next` to version `9.4.4`
I am not sure what is the implication of locking that version in another use cases or during deployment

Shall I include temporary fix for monorepo in this PR?

The issue i encounter on monorepo seems related to https://github.com/vercel/next.js/issues/15616

**Comment by kyle-mccarthy** [comment]
I will merge this in! I am honestly not sure what the issue is with the mono repo. That is a community contribution which I'm not familiar with. However, I appreciate the time that you took with this issue as well as debugging the other!

**Comment by sergioutama** [comment]
You've done great job with this package, and i really appreciate it 👍

**Pull request merged**
